
name: CI Testing

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        run: sudo apt-get -y install python3

      - name: Latest pip version 
        run: sudo apt install -y python3-pip

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Install pennylane by hand
        run: pip3 install pennylane --upgrade

      - name: Execute tests 
        run: bash runtests.sh
